import QtQuick

QtObject {
    readonly property string videoLabel: "视频"
    readonly property string shortVideoLabel: "短视频"
    readonly property string siteLabel: "站点"
    readonly property string typeLabel: "类型"
    readonly property string playLabel: "播放"
    readonly property string actorPrefix: "演员: "
    readonly property string clickPlayLabel: "点击播放"
    readonly property string copyLabel: "复制"
    readonly property string downloadLabel: "下载"
    readonly property string refreshLabel: "刷新"
    readonly property string searchLabel: "搜索"
    readonly property string keywordPlaceholder: "关键词"

    readonly property string imageTitle: "随机图片"
    readonly property string imageCurrentPrefix: "当前图片源："
    readonly property string imageEmptyDescription: "从图片类型站点获取图片，支持 JSON / XML / URL / 302 / 直图接口"
    readonly property string imageChangeLabel: "换一张"
    readonly property string imageRefreshModeLabel: "刷新模式"
    readonly property string imageSameSourceRefresh: "同源刷新"
    readonly property string imageSwitchSourceRefresh: "换源刷新"
    readonly property string imageAutoRefreshLabel: "自动刷新"
    readonly property string imageHint: "点击“换一张”从图片站点获取图片"
    readonly property var imageRefreshIntervals: ["关闭", "1秒", "3秒", "5秒"]

    readonly property string memeTitle: "表情包"
    readonly property string memeDescription: "搜索表情包或随机加载龙图，支持图片直链、JSON 和文本 URL 响应。"
    readonly property string memeDragonLabel: "龙图"
    readonly property string memeHint: "搜索“龙图”，或点击“龙图”加载随机表情"
    readonly property string memePreviewTitle: "表情包预览"

    readonly property string shortVideoSitesTitle: "短视频站点"
    readonly property string shortVideoSitesDescription: "选择一个短视频源，点击卡片直接播放"
    readonly property string shortVideoRandomTitle: "随机短视频"
    readonly property string shortVideoRandomDescription: "对接 yujn 直出视频接口，点击后自动进入播放器播放。"
    readonly property string shortVideoCurrentPlay: "当前选择 · 点击播放"
    readonly property string shortVideoRandomPlay: "点击播放随机短视频"
    readonly property string shortVideoNoSites: "暂无短视频站点，请到站点页面新增类型为“短视频站点”的接口"
    readonly property string videoSearchTitle: "视频搜索"
    readonly property string videoSearchHint: "搜索视频站点内容，点击进入详情页选集播放"
    readonly property string shortVideoSearchHint: "选择一个短视频站点，点击卡片直接播放"
    readonly property string playbackTypeLabel: "播放类型"
    readonly property string playModeOnce: "单次"
    readonly property string playModeSame: "同类自动"
    readonly property string playModeRandom: "随机类型"

    readonly property string voiceTitle: "语音"
    readonly property string voiceDescription: "选择一个语音接口播放；整点报时会自动传入本机当前时间。"

    readonly property string musicTitle: "音乐"
    readonly property string musicHallTitle: "音乐馆"
    readonly property string musicDescription: "支持网易云 / QQ 音乐搜索、歌单加载、在线播放和歌词显示。"
    readonly property string musicStudioDescription: "搜索歌曲、加载歌单、播放音乐和查看歌词都在这里。像把一张唱片轻轻放上转盘。"
    readonly property string musicSearchPlaceholder: "输入歌曲名、歌手或关键字，例如：秦时明月"
    readonly property string musicProSearchPlaceholder: "搜索歌曲 / 歌手 / 关键词，例如：秦时明月"
    readonly property string musicPlaylistPlaceholder: "输入歌单 ID，例如：6907557348 / 7326220405"
    readonly property string musicPlaylistCompactPlaceholder: "歌单 ID"
    readonly property string musicLoadPlaylist: "加载歌单"
    readonly property string musicEmptyResults: "搜索歌曲或输入歌单 ID 加载播放列表"
    readonly property string musicNoTrack: "未播放音乐"
    readonly property string musicLyricsEmpty: "歌词会在播放后显示"
    readonly property string musicPlaylistTitle: "播放列表"
    readonly property string musicTrackUnit: " 首"
    readonly property string musicUnknownArtist: "未知歌手"
    readonly property string musicNoPlaylist: "没有播放列表"
    readonly property string musicNoPlaylistHint: "搜索歌曲，或者输入歌单 ID 后点击加载。"
    readonly property string musicSelectTrackHint: "选择一首歌开始播放"
    readonly property string musicPauseLabel: "暂停"
    readonly property string musicStopLabel: "停止"
    readonly property string musicFolderLabel: "文件夹"
    readonly property string musicVolumeLabel: "音量"
    readonly property string musicLyricsLabel: "歌词"
    readonly property string musicProcessing: "正在处理音乐请求..."
    readonly property string neteaseLabel: "网易云"
    readonly property string qqMusicLabel: "QQ音乐"
    readonly property string musicIcon: "♪"
    readonly property string playIcon: "▶"
    readonly property string closeIcon: "×"
}